### ISSUE TITLE
DNS configuration to prevent emails being spam

### ISSUE THREAD

**Issue by eamirgh** [d1ceward/dokku-posteio#2]
First of all I want to thank you for maintaining this awesome plugin or app for dokku.
After a fresh installation, all sent emails are marked as spam. On **Poste.io** documentation has a [DNS configuration](https://poste.io/doc/configuring-dns) page which is a guide to avoid emails being marked as spam, could you please add a command to get the records especially DKIM record?

**Comment by D1ceWard** [comment]
Hello,
I don't understand your demand, DKIM record are managed by your DNS provider...
Do you want a command doing a simple DNS lookup ? or something more complicated ?

**Comment by eamirgh** [comment]
No, I will  make a PR asap.

**Comment by scwall** [comment]
Hello I just wanted to answer this help, the configuration part is integrated directly in poste.io which gives the adequate configurations to add the dkims keys and the rest of the configuration, it is in the settings part.

The use of mailtester is perfect to get the missing parameters (dmarc,etc..).

Last little thing, mails almost always fall in spam at microsoft, even with 10/10 on mailtester or others. I don't know if it's their policy to force the services but at work we had to write to microsoft (even though we are a partner) so that it would not be blacklisted anymore

**Comment by nwokolawrence6** [comment]
How do i use the API , when ever i try it returns 401Unauthorized
